### ISSUE TITLE
[Documentation]: Explain what entries are expected in the agenda/how to map agenda entries.

### ISSUE THREAD

**Issue by mdeweerd** [idaho/hassio-trash-card#162]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

It's not clear how the collection types are mapped with regards to the agenda.

I've searched for a forum entry but could not find one.

It's an issue to use the card if it's not sufficiently documented.

### Describe the solution you'd like

Explain how a calender entry should be created and how it is mapped to the card.

**Comment by clawfire** [comment]
First of all, you need a calendar entity configured and accessible by HA. It can be a local or remote (eg. Google calendar) that doesn't matter. 

## Create events in your calendar
In order for the Trash card to display informations, they need to be existing in a calendar. Here's some rules to follow when creating the events in your calendar: 

1. It must be entire day events (only form of events supported at the moment)
2. You must use the same event name for the same method of collection. You'll map them later. Right now, the card support up to 5 different type of collections
3. You can use repeating events, that's totally fine.

## Trash card configuration
Here's simple steps to follow to configure the trash card, we'll go throw all the differents configuration field with you: 
![O](https://github.com/idaho/hassio-trash-card/assets/1178/3610465f-0b9a-4ded-8621-9691c845acd3)

1. First, you need to select your calendar entity in the first field `Entity` (can be different because it's translated in your own language). 
2. Then, for all the different collection, you'll have to fill those fiels: 
    a. `Label` is the text you want to be displayed in your card. It can be anything
    b. `Icon` is the icon you can to be used in your card. You can select through the availabla HA icons, and even start typing to search
    c. `Color` is the color you want your card to be. ⚠️ it's not gonna be the color of the icon but of the card itself
    d. `Pattern` is the event title you used when creating events in your calendar. For example, for recycling, mine is "PMC", because that's the event name in my calendar.
3. `day style` is how to display the information. Full date or "in xx days"
4. `drop today events from` is at which hour you want to stop displaying today's collection
5. `next days` is how many days in the future the card will look up. If there is no upcoming event in the next XX days you selected here, **the card will not display at all**. 

![O](https://github.com/idaho/hassio-trash-card/assets/1178/074164cd-9865-4edc-be48-216b7acba3e5)

**Comment by mdeweerd** [comment]
@clawfire Thank you.  It clarifies that the "Modèle de détection" has to be some text given in the calendar event.
I assumed that I had to name the calendar event after the fields in the yaml configuration (recycle/waste/...).

I think that for the french translation we should find something better than "Modèle de détection".

It is not clear if this is a pattern such as "P.*" or just the textual string that needs to match exactly what is in the calendar.
Maybe it should reuse the calendar's label "Event name" - it may be different because I find this in French which would be summary/title?:
![image](https://github.com/idaho/hassio-trash-card/assets/1504752/bcb42fee-20a8-453a-bcdb-43ca0975a5c3) .

I think it is helpful to use that (or such an image) in the documentation because there are several languages, but the position will be the same.

**Comment by clawfire** [comment]
I agree that "modèle de détection" is vague for french speaker. I used the exact name of my events. Didn't try like regex 😁
