### ISSUE TITLE
[Feature]: show all entries for the same type

### ISSUE THREAD

**Issue by forreggbor** [idaho/hassio-trash-card#194]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

If I set the "Days in the future" to for example 7 days and there are 2 pcs of "waste" collection on two different days only the first one on the closest days is displayed. For example today is 1st of Feb. There are waste collection on 3rd and 6th of Feb. Only the one on 3rd is displayed.

### Expected Behavior

Display both (all) collections entries during the period selected in "Days on the future" .

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: any
- HA Version: core 2024.2.1
- TrashCard: 2.0.0-beta1
```

**Comment by idaho** [comment]
Hey @forreggbor are the waste collection matching the same pattern, the same type of waste? Currently there will be only shown one event per type or if its not matching any pattern they are grouped by the description. 

That means e.g.

Today is the 1st of Feb and you have on the 3rd and 6th a waste collection which matches "waste" it will only show the closest one.
If both match different event like one is "waste" and the other one is "recycle" it should show both.

I've already planned a option to disable this grouping. So that you will see all matched events per type if this is disabled.

**Comment by forreggbor** [comment]
Thank you. Would be usefull to disable grouping and see each entry. 
I'll wait for this feature. :-)

**Comment by forreggbor** [comment]
In case of "Others" category it's not groupping. So I can add any amount and all entries are displayed as I would expect for named categoris (wast, organic, etc.)

**Comment by idaho** [comment]
@forreggbor will be in the next beta release (2.0.0-beta.2)
