### ISSUE TITLE
[Feature]: 2 Events on one day

### ISSUE THREAD

**Issue by Larrysansan97** [idaho/hassio-trash-card#219]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

No

### Describe the solution you'd like

In my region Paper and organic is on the same day. Id Like to Display them both. At the Moment Just one Item ist displayed.

**Comment by idaho** [comment]
Hey @Larrysansan97 please check the latest beta release (Version 2.0.0-beta.4) . If you need help on how to install the latest beta version, have a look at https://hacs.xyz/docs/faq/beta/ .

In the latest beta you are able to activate a debug mode. 

**How you can activate the debug mode**

Edit the trash-card item you have added, open the yaml editor and add `debug: true` to the yaml configuration. 
After that you will see some debug information. At the right top corner you will see a copy icon. Click on this icon to copy the debug information to you clipboard. After that you can remove the added debug line from your yaml configuration.

Please feel free to share your yaml configuration and the debug data so that i'm able to find the reason.

**Comment by jomaskm** [comment]
> ### Requirements
> * [x]  I have updated Mushroom to the latest available version
> * [x]  I did a search to see if there is a similar issue or if a pull request is open.
> 
> ### Is your feature request related to a problem?
> No
> 
> ### Describe the solution you'd like
> In my region Paper and organic is on the same day. Id Like to Display them both. At the Moment Just one Item ist displayed.
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Additional context
> _No response_

This is a feature that is needed for me to be able to make use of the card as well.

For example: In my area "Trash" and "Organic" is collected on the same day, but only one is shown on the card.

Otherwise a nice looking card, but not something I'm able to make use of because of this.

**Comment by roberttco** [comment]
Until this is updated, you can use a horizontal stack card and put two or more trash cards in the stack.  Change each card's configuration to filter on patterns and configure the pattern for that card.  for example:

`type: horizontal-stack
cards:
  - drop_todayevents_from: '10:00:00'
    next_days: 7
    settings:
      recycle:
        icon: mdi:recycle-variant
        color: green
        pattern: Recycling day
    day_style: counter
    type: custom:trash-card
    entity: calendar.republic_services
    filter_events: true
    fill_container: false
    use_summary: false
    layout: horizontal
  - drop_todayevents_from: '10:00:00'
    next_days: 7
    settings:
      waste:
        icon: mdi:trash-can-outline
        color: blue
        pattern: Trash
    day_style: counter
    type: custom:trash-card
    entity: calendar.republic_services
    filter_events: true
    layout: horizontal
    fill_container: false
    use_summary: true`

**Comment by idaho** [comment]
@jomaskm @roberttco check the latest beta (If you need help on how to install the latest beta version, have a look at https://hacs.xyz/docs/faq/beta/), in there it's already implemented (#145 ). 

I hope the Version 2 could be release next week with many new features. Need to update the readme and check translations. Help would be welcome (#209 )

**Comment by idaho** [comment]
Release in version 2.0.0 which is now available

**Comment by roberttco** [comment]
Thank you!  I'm sorry I didn't get a chance to test the beta.
