### ISSUE TITLE
Add ability to show 'next scheduled event' as Day of the Week (E, EE, EEE, EEEEE) rather than a date or 'days to'

### ISSUE THREAD

**Issue by corksftw** [idaho/hassio-trash-card#382]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

I need to use the EEEE date format to display the name of the day the trash will be collected. For example the organic on Tuesday.
![image](https://github.com/user-attachments/assets/05fa96b2-3659-4806-ae90-01c0373b0586)

### Describe the solution you'd like

Possibility to use EEEE format in custom date format to display only the day name in the card

**Comment by Arcane1980** [comment]
@idaho this is ALSO a great feature request. For those of us who run our lives/schedules on "days of the week" rather than date, it would be great to have the option to show the "Weekday" even if this is an additional drop down option rather than added to the custom date options as long as the option is available.

ie:
Appearance > Show Event Time As > Date
                                                         > Days To
                                                         > **Weekday**
                                                         > Custom

Second this Feature request!
