### ISSUE TITLE
[Feature]: Don't show empty TrashCard

### ISSUE THREAD

**Issue by Riza-Aslan** [idaho/hassio-trash-card#411]
### Requirements

- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

No

### Describe the solution you'd like

If there is no Trash entry in the calendar for the given time period, the card is still using blank space on the dashboard (without showing any TrashCards). It would be better to have an option to don't show the card, if it is empty. For example, the [official entity filter](https://www.home-assistant.io/dashboards/entity-filter/) card does have the option: "show_empty: false"

### Describe alternatives you've considered

A conditional card would also be possible, but then I would have to work with a template-helper. If I set the TrashCard to show the next 3 days, I would need to create a template-boolean-helper which is getting true if the next event starts within 3 days. But I don't know how this template would look like.

**Comment by idaho** [comment]
I will hide it if nothing is available

During editing the view we need to have a placeholder, otherwise you are not able to modify some settings till a event appears
![Screenshot 2024-10-02 at 16 34 46](https://github.com/user-attachments/assets/a30b04fc-1937-4ccc-902b-f3c777f524fe)

If you're done with editing it will look like that
![Screenshot 2024-10-02 at 16 34 51](https://github.com/user-attachments/assets/ac0214d0-f7d0-4ce0-8e05-67c4460467ab)
